baseURL = "http://www.xucaixu.com"
languageCode = "en-us"
title = "Travis"
theme = "hugo-travis"



[[menu.main]]
    name = "个人介绍"
    url = "/"
    weight = 1

[[menu.main]]
    name = "随笔笔记"
    url = "/note"
    weight = 2

[[menu.main]]
    name = "一些整理"
    url = "/shares"
    weight = 3

[[menu.main]]
    name = "关注链接"
    url = "/links"
    weight = 4
